language: node_js
node_js:
- '14'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - main
deploy:
  provider: heroku
  app: steam-jul-zas
  api_key:
    secure: KAY0ibCGYXHzNkJzFbI1EgsqDCfgFLU5xchlWywNBodRLSMBERrEFAC0IBeDgN3+3aW8DESqrC37Uc8KgQf/OpGgvE2C2Exg+tOB84XwSdlJWaEOV+/p6cJ5BBsS9HL4XoBerlnAoGGQSAn4ZlwQ7smHDr2SbxK9gzqwiE0hBA+OxAz8WOqubNDTgW3q1XD9wJ1ecVnVs47NJEtrdcWilaO6e6St5D4cWjKMJTO9hBqfXYdCxWpuBHsbM2X/x1zCSso7UZryt5p/4MTxKtc3+vH7bVOFLlIBR2hlOkesBJoFubhe/V98cBfd6dTeQsNN7wwnutCYp91eCj6GTVzGTRUYlvvg55Qbi+uMgp71eRaa4m4xKOAeQ7h8DnOhZZINRza2X0jhdXM8uhjvu+o8fZjGkgZMXjx9S4RsGuevigCmeu0BZktJv0SDdq4GWBGgdw8I5OmERiJm6KlTJaxVSyEORUG5cGR1ZFsmYiS9TCt+gvtPuJ7D9tIRxxapcvz3ZrniZ7sVvlOrhZ439LKBbt8n7HG3ixXPH+7RWXnizZbVhy8Mq17QH8pD7ugzr5ZgRWyO8zqUIRZWRmVUb0G22vmF4IsCK04MckKc2AohlUzK/6eSe56jpFK26xC8DL5X4NVHEaAQIX1OjQAyt2G7BENDIHbtVGhYgSaVxALnzwc=
